### ISSUE TITLE
URL do banco exposta

### ISSUE THREAD

**Issue by GuScarpim** [vbccha888/tech_challenge#1]
No commit https://github.com/vbccha888/tech_challenge/commit/4b443cba600ca18492b75a8276d4f92e2796ce3c, está mostrando a sua url do banco, o correto seria deletar esse commit para que não fique gravado essa alteração no log de commits.

Dá para fazer isso utilizando o git filter-repo ou git filter-branch.

**Comment by vbccha888** [comment]
Prof. Gustavo, agradeço pela orientação. Removi o commit indicado.
